### ISSUE TITLE
Bluethoo and Keyboard

### ISSUE THREAD

**Issue by Slider324** [BadWolf-alfa/RevolutionROMNougat#3]
Hola que tal yo tengo la vnl-53 y encerio esta de marvilla tu version, pero para mi mala suerte en el 53 no funcionan todo ejemplo termino la instalacion y no tiene keyboard, no se si sera por que todo lo instalo desde los 3 botones o cual sea el error, pero esto se soluciona con hisuit, pero el otro error que encuentro con esta version es que no funciona bluethoo espero estos errores se solucionen y si necesitan algun test con esta version con gusto les echo la mano

**Comment by BadWolf-alfa** [comment]
Cerramos el ticket, es por mala instalación. Esta especificado en el post que hay que instalar datafull y datafull desde el método de tres botones no se puede, ha de ser estando aun en MM.

Tendrás que hacer downgrade e instalar Nougat desde TWRP para poder tener todo.

Saludos.
