### ISSUE TITLE
Bluetooth and Motion Controls are not working

### ISSUE THREAD

**Issue by zorgon97** [BadWolf-alfa/RevolutionROMNougat#4]
I had  B336 Firmware on VNS-L31C432B336 P9 lite. Then I flashed RC2 using revolution nougat recovery. After that my bluetooth is not working and I checked motion controls.I can turn them on.but when I double tap or draw a gesture or cover screen nothing happens. I cant even turn on bluetooth.Today I updated it to RC3 and still same issues.
Yes I tried wipe,factory reset, reflash.but still same issues .please help me if you can

**Comment by BadWolf-alfa** [comment]
You don't flashed the data_full in Nougat installation. 

No it's caused by ROM the problem.

Issue clossed. 

Read al instructions, it's due of you failed installation the problem.
